export { About } from '@pages/About';
export { ContactUs } from '@pages/ContactUs';
export { Payment } from '@pages/Payment';
export { PrivacyPolicy } from '@pages/PrivacyPolicy';
export { ProductDetail } from '@pages/ProductDetail';
export { ReturnPolicy } from '@pages/ReturnPolicy';
export { RunWay } from '@pages/RunWay';
export { RunWayDetail } from '@pages/RunWayDetail';
export { Shop } from '@pages/Shop';
export { SignUp } from '@pages/SignUp';
export { TermAndCondition } from '@pages/TermAndCondition';
export { Home } from '@pages/Home';
export { ForgetPassword } from '@pages/ForgetPassword';
export { ResetPasswordForm } from "@pages/ResetPasswordForm";
export { Overview } from "@pages/Overview";
export { Account } from "@components/layouts/Account";
export { MyOrders } from "@components/layouts/MyOrders";
export { Addresses } from "@pages/Addresses";
export { Notify } from "@pages/Notify";
export { Wishlist } from "@pages/Wishlist";
export { Result } from "@pages/Result";
export { NewArrivals } from "@pages/NewArrivals";
export { MadeToOrder } from "@pages/MadeToOrder";
export {Collections} from "@pages/Collections";
export {News} from "@pages/News";
export {NewsDetails} from "@pages/NewsDetails";